name: 'Configure CMake'
description: 'Configures CMake build system'

inputs:
  config:
    description: 'Build configuration (Debug/Release)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VSINSTALL=%%i"
        call "%VSINSTALL%\Common7\Tools\VsDevCmd.bat" -arch=x64 -host_arch=x64
        where cmake
        cmake --version
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ inputs.config }} -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl

    - name: Configure CMake (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        which cmake
        cmake --version
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ inputs.config }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++